import Head from "next/head"
import Editor, { DiffEditor } from '@monaco-editor/react';
import { Feed } from "../../components/feed/feed";
import { TranscriptDetail } from "../../components/transcript/transcript-detail";
import Link from "next/link";
import { Private } from "../../components/private";
import { useTranscript } from "../../services/transcript";

const Transcript = ({ id }) => {
    const { data: transcript } = useTranscript(id)

    return (
        <Private>
            <Head>
                <title>Viewer | Transcript Details</title>
            </Head>
            <h1 className="text-2xl">{transcript?.name}</h1>
            <div className="flex flex-col gap-4">
                <div className="flex gap-4">
                    <div className="flex flex-col gap-4 w-1/2 bg-white p-4 rounded-md">
                        <TranscriptDetail transcript={transcript} />
                    </div>
                    <div className="flex flex-col gap-4 w-1/2 bg-white p-4 rounded-md">
                        <div>
                            <h2 className="text-xl">
                                Pipeline
                            </h2>
                            <p className="mt-1 text-sm text-gray-500">
                                Pipeline configuration used for this run.
                            </p>
                        </div>
                        <Feed config={transcript?.run.config} />
                    </div>
                </div>
                <div className="flex flex-col gap-4 bg-white p-4 rounded-md">
                    <div>
                        <h2 className="text-xl">
                            Output Comparison
                        </h2>
                        <p className="mt-1 text-sm text-gray-500">
                            Shows the differences between the original transcript (Reference) and the transcript generated by the model (Hypothesis).
                        </p>
                        <Link href={`/transcripts/diff/${transcript?.id}`} className="underline text-sky-600 text-sm">
                            View larger
                        </Link>
                    </div>
                    <div className="flex">
                        <div className="w-full">
                            <h3 className="text-lg">Reference</h3>
                        </div>
                        <div className="w-full">
                            <h3 className="text-lg">Hypothesis</h3>
                        </div>
                    </div>
                    <DiffEditor
                        className="py-4 h-[20vh]"
                        original={transcript?.reference}
                        modified={transcript?.hypothesis}
                    />
                </div>
                <div className="flex flex-col gap-4 bg-white p-4 rounded-md">
                    <div>
                        <h2 className="text-xl">
                            Configuration
                        </h2>
                        <p className="mt-1 text-sm text-gray-500">
                            Configuration used for this run.
                        </p>
                    </div>
                    {transcript?.run.config &&
                        <Editor
                            className="py-4 h-[70vh]"
                            language="json"
                            value={JSON.stringify(transcript?.run.config, null, 4)}
                        />
                    }
                </div>
            </div>
        </Private>
    )
}

export async function getServerSideProps({ query }) {
    return {
        props: {
            id: query.id
        },
    }
}

export default Transcript